# Generated by Django 5.0.2 on 2024-02-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_subject_code_subject_subject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(max_length=10)),
                ('stream', models.CharField(max_length=10)),
            ],
        ),
    ]
