# Generated by Django 5.0.2 on 2024-02-16 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_class_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='id',
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.class'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
