# Generated by Django 5.0.2 on 2024-02-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subject_id_alter_subject_subject_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_number', models.CharField(max_length=20)),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_gender', models.CharField(max_length=10)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('teacher_phone', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('joinin_date', models.DateField()),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('tsc_no', models.CharField(max_length=20)),
                ('subject_combination', models.CharField(max_length=255)),
            ],
        ),
    ]
