# Generated by Django 5.0.2 on 2024-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joinin_date',
            field=models.DateField(verbose_name='%Y-%m-%d'),
        ),
    ]
