# Generated by Django 5.0.2 on 2024-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_teacher_joinin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joinin_date',
            field=models.CharField(max_length=20),
        ),
    ]
