# Generated by Django 5.0.2 on 2024-02-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=10)),
                ('joining_date', models.DateField()),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('religion', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('Class', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='student_photos/')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=15)),
                ('parent_address', models.TextField()),
                ('parent_relationship', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
