# Generated by Django 5.0.2 on 2024-02-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_students_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='student_photos/default.jpg', upload_to='student_photos/'),
        ),
    ]
