# Generated by Django 5.0.2 on 2024-02-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_students_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='student_photos/'),
        ),
    ]
