# Generated by Django 5.0.2 on 2024-03-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_teacher_image_teacher_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_picture',
            new_name='image',
        ),
    ]
