# Generated by Django 5.0.2 on 2024-03-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_profile_picture_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='teacher_images'),
        ),
    ]
