# Generated by Django 5.0.2 on 2024-03-01 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Class',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.class'),
        ),
    ]
