# Generated by Django 5.0.2 on 2024-03-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_students_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classes',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='Class',
            new_name='Classes',
        ),
    ]
