# Generated by Django 5.0.2 on 2024-03-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_class_classes_rename_class_students_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='Classes',
            new_name='subject_class',
        ),
    ]
