# Generated by Django 5.0.2 on 2024-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_subject_class_students_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='joining_date',
            field=models.CharField(max_length=20),
        ),
    ]
